module.exports = {
  printWidth: 120, 
  tabWidth: 2, 
  semi: true, 
  singleQuote: true, 
  trailingComma: "none", 
  bracketSpacing: true, 
  jsxSingleQuote: true,
  proseWrap: "never", 
  endOfLine: "lf",
  plugins: ["./node_modules/prettier-plugin-sort-imports/dist/index.js"],
  sortingMethod: "alphabetical",
  pluginSearchDirs: ["./node_modules"],
  importOrder: ["^[a-zA-Z]"],
};
